import cover from "../images/quizCover.jpg";
export const data = [
	{
		id: 1,
		createdBy: "Admin",
		name: "Adventure",
		questions: 12,
		duration: "10min",
		cover: cover,
		topics: ["Basic", "Adventure", "First"],
		difficulty: "easy",
	},
	{
		id: 2,
		createdBy: "Admin",
		name: "Adventure",
		questions: 12,
		duration: "10min",
		cover: cover,
		topics: ["Basic", "Adventure", "First"],
		difficulty: "easy",
	},
	{
		id: 3,
		createdBy: "Admin",
		name: "Adventure",
		questions: 12,
		duration: "10min",
		cover: cover,
		topics: ["Basic", "Adventure", "First"],
		difficulty: "easy",
	},
	{
		id: 4,
		createdBy: "Admin",
		name: "Adventure",
		questions: 12,
		duration: "10min",
		cover: cover,
		topics: ["Basic", "Adventure", "First"],
		difficulty: "high",
	},
	{
		id: 5,
		createdBy: "Admin",
		name: "Adventure",
		questions: 12,
		duration: "10min",
		cover: cover,
		topics: ["Basic", "Adventure", "First"],
		difficulty: "high",
	},
	{
		id: 6,
		createdBy: "Admin",
		name: "Adventure",
		questions: 12,
		duration: "10min",
		cover: cover,
		topics: ["Basic", "Adventure", "First"],
		difficulty: "med",
	},
	{
		id: 7,
		createdBy: "Admin",
		name: "Adventure",
		questions: 12,
		duration: "10min",
		cover: cover,
		topics: ["Basic", "Adventure", "First"],
		difficulty: "med",
	},
	{
		id: 8,
		createdBy: "Admin",
		name: "Adventure",
		questions: 12,
		duration: "10min",
		cover: cover,
		topics: ["Basic", "Adventure", "First"],
		difficulty: "high",
	},
	{
		id: 9,
		createdBy: "Admin",
		name: "Adventure",
		questions: 12,
		duration: "10min",
		cover: cover,
		topics: ["Basic", "Adventure", "First"],
		difficulty: "med",
	},
	{
		id: 10,
		createdBy: "Admin",
		name: "Adventure",
		questions: 12,
		duration: "10min",
		cover: cover,
		topics: ["Basic", "Adventure", "First"],
		difficulty: "easy",
	},
];
